package org.jeecg.modules.kol.util;

import lombok.extern.slf4j.Slf4j;
import org.jeecg.common.util.oConvertUtils;
import org.jeecg.modules.kol.entity.KolCategory;
import org.jeecg.modules.kol.entity.KolTagCategory;
import org.springframework.stereotype.Component;

import java.util.*;

/**
 * 分类递归检查工具类
 * 用于检测和预防树形结构中的循环引用问题
 *
 * @author AutoGenerated
 * @since 2024-01-01
 */
@Slf4j
@Component
public class CategoryRecursionChecker {

    private static final int MAX_RECURSION_DEPTH = 1000;
    
    /**
     * 检查分类是否存在循环引用
     * 
     * @param categories 分类列表
     * @return true表示存在循环引用，false表示正常
     */
    public static boolean hasCircularReference(List<KolCategory> categories) {
        if (oConvertUtils.listIsEmpty(categories)) {
            return false;
        }
        
        Map<String, String> parentMap = new HashMap<>();
        Set<String> visited = new HashSet<>();
        Set<String> recursionStack = new HashSet<>();
        
        // 构建parent_id映射
        for (KolCategory category : categories) {
            if (category.getId() != null && category.getParentId() != null) {
                parentMap.put(category.getId(), category.getParentId());
            }
        }
        
        // 检查每个节点
        for (String nodeId : parentMap.keySet()) {
            if (!visited.contains(nodeId)) {
                if (hasCycle(nodeId, parentMap, visited, recursionStack)) {
                    log.warn("检测到分类循环引用，节点ID: {}", nodeId);
                    return true;
                }
            }
        }
        
        return false;
    }
    
    /**
     * 检查标签分类是否存在循环引用
     * 
     * @param categories 标签分类列表
     * @return true表示存在循环引用，false表示正常
     */
    public static boolean hasCircularReferenceForTag(List<KolTagCategory> categories) {
        if (oConvertUtils.listIsEmpty(categories)) {
            return false;
        }
        
        Map<String, String> parentMap = new HashMap<>();
        Set<String> visited = new HashSet<>();
        Set<String> recursionStack = new HashSet<>();
        
        // 构建parent_id映射
        for (KolTagCategory category : categories) {
            if (category.getId() != null && category.getParentId() != null) {
                parentMap.put(category.getId(), category.getParentId());
            }
        }
        
        // 检查每个节点
        for (String nodeId : parentMap.keySet()) {
            if (!visited.contains(nodeId)) {
                if (hasCycle(nodeId, parentMap, visited, recursionStack)) {
                    log.warn("检测到标签分类循环引用，节点ID: {}", nodeId);
                    return true;
                }
            }
        }
        
        return false;
    }
    
    /**
     * 递归检查循环引用
     */
    private static boolean hasCycle(String nodeId, Map<String, String> parentMap, 
                                  Set<String> visited, Set<String> recursionStack) {
        if (recursionStack.contains(nodeId)) {
            return true; // 发现循环
        }
        
        if (visited.contains(nodeId)) {
            return false; // 已经检查过的节点
        }
        
        visited.add(nodeId);
        recursionStack.add(nodeId);
        
        String parentId = parentMap.get(nodeId);
        if (parentId != null && !parentId.equals("0")) {
            if (hasCycle(parentId, parentMap, visited, recursionStack)) {
                return true;
            }
        }
        
        recursionStack.remove(nodeId);
        return false;
    }
    
    /**
     * 检查递归深度是否超过限制
     * 
     * @param categoryId 起始分类ID
     * @param categories 所有分类列表
     * @return true表示深度超限，false表示正常
     */
    public static boolean isRecursionTooDeep(String categoryId, List<KolCategory> categories) {
        if (oConvertUtils.isEmpty(categoryId) || oConvertUtils.listIsEmpty(categories)) {
            return false;
        }
        
        Map<String, List<String>> childrenMap = buildChildrenMap(categories);
        return checkDepth(categoryId, childrenMap, 0) > MAX_RECURSION_DEPTH;
    }
    
    /**
     * 检查标签分类递归深度是否超过限制
     * 
     * @param categoryId 起始分类ID
     * @param categories 所有标签分类列表
     * @return true表示深度超限，false表示正常
     */
    public static boolean isRecursionTooDeepForTag(String categoryId, List<KolTagCategory> categories) {
        if (oConvertUtils.isEmpty(categoryId) || oConvertUtils.listIsEmpty(categories)) {
            return false;
        }
        
        Map<String, List<String>> childrenMap = buildChildrenMapForTag(categories);
        return checkDepth(categoryId, childrenMap, 0) > MAX_RECURSION_DEPTH;
    }
    
    /**
     * 构建子节点映射关系
     */
    private static Map<String, List<String>> buildChildrenMap(List<KolCategory> categories) {
        Map<String, List<String>> childrenMap = new HashMap<>();
        
        for (KolCategory category : categories) {
            String parentId = category.getParentId() != null ? category.getParentId() : "0";
            childrenMap.computeIfAbsent(parentId, k -> new ArrayList<>()).add(category.getId());
        }
        
        return childrenMap;
    }
    
    /**
     * 构建标签分类子节点映射关系
     */
    private static Map<String, List<String>> buildChildrenMapForTag(List<KolTagCategory> categories) {
        Map<String, List<String>> childrenMap = new HashMap<>();
        
        for (KolTagCategory category : categories) {
            String parentId = category.getParentId() != null ? category.getParentId() : "0";
            childrenMap.computeIfAbsent(parentId, k -> new ArrayList<>()).add(category.getId());
        }
        
        return childrenMap;
    }
    
    /**
     * 递归计算树的深度
     */
    private static int checkDepth(String nodeId, Map<String, List<String>> childrenMap, int currentDepth) {
        if (currentDepth > MAX_RECURSION_DEPTH) {
            return currentDepth;
        }
        
        List<String> children = childrenMap.getOrDefault(nodeId, Collections.emptyList());
        if (children.isEmpty()) {
            return currentDepth;
        }
        
        int maxDepth = currentDepth;
        for (String childId : children) {
            int childDepth = checkDepth(childId, childrenMap, currentDepth + 1);
            maxDepth = Math.max(maxDepth, childDepth);
        }
        
        return maxDepth;
    }
    
    /**
     * 获取可能导致循环引用的节点信息
     * 
     * @param categories 分类列表
     * @return 循环引用的节点ID列表
     */
    public static List<String> getCircularNodes(List<KolCategory> categories) {
        List<String> circularNodes = new ArrayList<>();
        if (oConvertUtils.listIsEmpty(categories)) {
            return circularNodes;
        }
        
        Map<String, String> parentMap = new HashMap<>();
        Set<String> visited = new HashSet<>();
        Set<String> recursionStack = new HashSet<>();
        
        // 构建parent_id映射
        for (KolCategory category : categories) {
            if (category.getId() != null && category.getParentId() != null) {
                parentMap.put(category.getId(), category.getParentId());
            }
        }
        
        // 检查每个节点
        for (String nodeId : parentMap.keySet()) {
            if (!visited.contains(nodeId)) {
                if (detectCycleAndCollect(nodeId, parentMap, visited, recursionStack, circularNodes)) {
                    // 清理临时集合，准备下一轮检测
                    visited.clear();
                    recursionStack.clear();
                }
            }
        }
        
        return circularNodes;
    }
    
    /**
     * 检测循环并收集循环节点
     */
    private static boolean detectCycleAndCollect(String nodeId, Map<String, String> parentMap,
                                               Set<String> visited, Set<String> recursionStack,
                                               List<String> circularNodes) {
        if (recursionStack.contains(nodeId)) {
            // 发现循环，收集循环路径上的节点
            circularNodes.add(nodeId);
            return true;
        }
        
        if (visited.contains(nodeId)) {
            return false;
        }
        
        visited.add(nodeId);
        recursionStack.add(nodeId);
        
        String parentId = parentMap.get(nodeId);
        if (parentId != null && !parentId.equals("0")) {
            if (detectCycleAndCollect(parentId, parentMap, visited, recursionStack, circularNodes)) {
                circularNodes.add(nodeId);
                return true;
            }
        }
        
        recursionStack.remove(nodeId);
        return false;
    }
}